server:
  port: 8305
spring:
  application:
    name: service-vod
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
aliyun:
  vod:
    file:
      keyid: LTAI4G71k9KU8mqGAPqzpxok
      keysecret: g89Mk3kdFpOV0jiaKdU3ZlsZQmIM3q