server:
  port: 8333

spring:
  application:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true   # 发现路由
      routes:
      - id: service-acl
        uri: lb://service-acl
        predicates:
      - Path=/*/acl/**    # 路径匹配
      - id: service-edu
        uri: lb://service-edu
        predicates:
      - Path=/eduservice/**
      - id: service-ucenter
        uri: lb://service-ucenter
        predicates:
      - Path=/ucenter/**
    nacos:
      discovery:
        server-addr: localhost:8848

